name: "[Internal] Checkout foxglove-sdk"
description: >
  For internal Foxglove use only. Not publicly supported.
  Checks out foxglove-sdk at the action's pinned ref.

inputs:
  path:
    description: Where to check out the repository
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: ln -s "$GITHUB_ACTION_PATH/../../.." "${{ inputs.path }}"
