"""
This module defines channels to easily log messages conforming to well-known Foxglove schemas.

See the :py:mod:`foxglove.schemas` module for available definitions.
"""

# Generated by https://github.com/foxglove/foxglove-sdk
from foxglove._foxglove_py.channels import ArrowPrimitiveChannel
from foxglove._foxglove_py.channels import CameraCalibrationChannel
from foxglove._foxglove_py.channels import CircleAnnotationChannel
from foxglove._foxglove_py.channels import ColorChannel
from foxglove._foxglove_py.channels import CompressedImageChannel
from foxglove._foxglove_py.channels import CompressedVideoChannel
from foxglove._foxglove_py.channels import CubePrimitiveChannel
from foxglove._foxglove_py.channels import CylinderPrimitiveChannel
from foxglove._foxglove_py.channels import FrameTransformChannel
from foxglove._foxglove_py.channels import FrameTransformsChannel
from foxglove._foxglove_py.channels import GeoJsonChannel
from foxglove._foxglove_py.channels import GridChannel
from foxglove._foxglove_py.channels import ImageAnnotationsChannel
from foxglove._foxglove_py.channels import KeyValuePairChannel
from foxglove._foxglove_py.channels import LaserScanChannel
from foxglove._foxglove_py.channels import LinePrimitiveChannel
from foxglove._foxglove_py.channels import LocationFixChannel
from foxglove._foxglove_py.channels import LogChannel
from foxglove._foxglove_py.channels import ModelPrimitiveChannel
from foxglove._foxglove_py.channels import PackedElementFieldChannel
from foxglove._foxglove_py.channels import Point2Channel
from foxglove._foxglove_py.channels import Point3Channel
from foxglove._foxglove_py.channels import PointCloudChannel
from foxglove._foxglove_py.channels import PointsAnnotationChannel
from foxglove._foxglove_py.channels import PoseChannel
from foxglove._foxglove_py.channels import PoseInFrameChannel
from foxglove._foxglove_py.channels import PosesInFrameChannel
from foxglove._foxglove_py.channels import QuaternionChannel
from foxglove._foxglove_py.channels import RawAudioChannel
from foxglove._foxglove_py.channels import RawImageChannel
from foxglove._foxglove_py.channels import SceneEntityChannel
from foxglove._foxglove_py.channels import SceneEntityDeletionChannel
from foxglove._foxglove_py.channels import SceneUpdateChannel
from foxglove._foxglove_py.channels import SpherePrimitiveChannel
from foxglove._foxglove_py.channels import TextAnnotationChannel
from foxglove._foxglove_py.channels import TextPrimitiveChannel
from foxglove._foxglove_py.channels import TriangleListPrimitiveChannel
from foxglove._foxglove_py.channels import Vector2Channel
from foxglove._foxglove_py.channels import Vector3Channel

__all__ = [
    "ArrowPrimitiveChannel",
    "CameraCalibrationChannel",
    "CircleAnnotationChannel",
    "ColorChannel",
    "CompressedImageChannel",
    "CompressedVideoChannel",
    "CubePrimitiveChannel",
    "CylinderPrimitiveChannel",
    "FrameTransformChannel",
    "FrameTransformsChannel",
    "GeoJsonChannel",
    "GridChannel",
    "ImageAnnotationsChannel",
    "KeyValuePairChannel",
    "LaserScanChannel",
    "LinePrimitiveChannel",
    "LocationFixChannel",
    "LogChannel",
    "ModelPrimitiveChannel",
    "PackedElementFieldChannel",
    "Point2Channel",
    "Point3Channel",
    "PointCloudChannel",
    "PointsAnnotationChannel",
    "PoseChannel",
    "PoseInFrameChannel",
    "PosesInFrameChannel",
    "QuaternionChannel",
    "RawAudioChannel",
    "RawImageChannel",
    "SceneEntityChannel",
    "SceneEntityDeletionChannel",
    "SceneUpdateChannel",
    "SpherePrimitiveChannel",
    "TextAnnotationChannel",
    "TextPrimitiveChannel",
    "TriangleListPrimitiveChannel",
    "Vector2Channel",
    "Vector3Channel",
]
