// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Apple {
    #[prost(string, optional, tag = "1")]
    pub color: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "2")]
    pub diameter: ::core::option::Option<i32>,
}
