mod connection;
mod participant;

use thiserror::Error;

pub(crate) use connection::{CloudConnection, CloudConnectionOptions};

/// An error type for errors generated by this crate.
#[derive(Error, Debug)]
#[non_exhaustive]
pub enum CloudError {
    /// An error occurred while writing to the stream.
    #[error(transparent)]
    StreamError(#[from] livekit::StreamError),
}
