// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { Time } from "./Time";

/** A single frame of an audio bit stream */
export type Audio = {
  /** Timestamp of audio frame */
  timestamp: Time;

  /**
   * Audio frame data
   * For packet-based audio codecs this data must begin and end on packet boundaries (no partial packets).
   * For PCM audio formats the samples in the data must be interleaved.
   */
  data: Uint8Array;

  /** Audio format. One of 'pcm-s16', 'opus', or 'mp4a.40.2' */
  format: string;

  /** Audio frame data */
  description: Uint8Array;

  /** Sample rate in Hz */
  sample_rate: number;

  /** Number of channels in the audio frame */
  number_of_channels: number;
};
