// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { AudioFormat } from "./AudioFormat";
import { Time } from "./Time";

/** A single frame of an audio bitstream */
export type Audio = {
  /** Timestamp of audio frame */
  timestamp: Time;

  /** Audio frame data */
  data: Uint8Array;

  /** Audio format */
  format: AudioFormat;

  /** Audio frame data */
  description: Uint8Array;

  /** Sample rate in Hz */
  sample_rate: number;

  /** Number of channels in the audio frame */
  number_of_channels: number;
};
