// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { Time } from "./Time";

/** A single frame of an audio bit stream */
export type Audio = {
  /** Timestamp of audio frame */
  timestamp: Time;

  /**
   * Audio frame data
   * For packet-based audio codecs this data must begin and end on packet boundaries (no partial packets).
   * For PCM audio formats the samples in the data must be interleaved and little-endian.
   */
  data: Uint8Array;

  /** Audio format. One of 'pcm-s16', 'opus', or 'mp4a.40.2' */
  format: string;

  /** Per-format metadata. Only needed for opus in an ogg container. */
  description: Uint8Array;

  /** Sample rate in Hz. Only needed for PCM formats. */
  sample_rate: number;

  /** Number of channels in the audio frame. Only needed for PCM formats. */
  number_of_channels: number;
};
