// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

/** An enumeration of supported audio formats */
export enum AudioFormat {
  /** Interleaved, signed 16-bit PCM */
  PCM_S16 = 0,

  /** Opus */
  OPUS = 1,

  /** MPEG-4 AAC LC */
  MP4A_40_2 = 2,
}
