// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { Time } from "./Time";

/** A single block of a compressed audio bitstream */
export type CompressedAudio = {
  /** Timestamp of the start of the audio block */
  timestamp: Time;

  /** Audio data */
  data: Uint8Array;

  /** Audio format. Only 'opus' is currently supported */
  format: string;

  /** Sample rate in Hz */
  sample_rate: number;

  /** Number of channels in the audio block */
  number_of_channels: number;
};
