// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { PackedElementField } from "./PackedElementField";
import { Pose } from "./Pose";
import { Time } from "./Time";

/** A compressed point cloud */
export type CompressedPointCloud = {
  /** Timestamp of point cloud */
  timestamp: Time;

  /** Frame of reference */
  frame_id: string;

  /** The origin of the point cloud relative to the frame of reference */
  pose: Pose;

  /** Number of bytes between points in the decoded `data`. This matches the decoded layout described by `fields`, not the codec bitstream layout. */
  point_stride: number;

  /** Fields in the decoded `data`. At least 2 coordinate fields from `x`, `y`, and `z` are required for each point's position; `red`, `green`, `blue`, and `alpha` are optional for customizing each point's color. */
  fields: PackedElementField[];

  /** Compressed point cloud data for exactly one point cloud sample */
  data: Uint8Array;

  /**
   * Point cloud compression format
   * 
   * Supported values: `cloudini`, `draco`
   */
  format: string;
};
