// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import type { Color } from "./Color.ts";
import type { Pose } from "./Pose.ts";
import type { Vector3 } from "./Vector3.ts";

/** A primitive representing a cube or rectangular prism */
export type CubePrimitive = {
  /** Position of the center of the cube and orientation of the cube */
  pose: Pose;

  /** Size of the cube along each axis */
  size: Vector3;

  /** Color of the cube */
  color: Color;
};
