// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

/** Type of an event property value */
export enum EventPropertyType {
  /** Single-line text */
  TEXT = 0,

  /** Multi-line text */
  MULTILINE_TEXT = 1,

  /** True/false */
  BOOLEAN = 2,

  /** Numeric value */
  NUMBER = 3,

  /** Single choice from options */
  SINGLE_SELECT = 4,

  /** Multiple choices from options */
  MULTI_SELECT = 5,
}
