// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { Duration } from "./Duration";
import { EventProperty } from "./EventProperty";
import { EventType } from "./EventType";
import { Time } from "./Time";

/** A discrete event that occurred at a specific time. An event may have zero duration (instantaneous) or a non-zero duration. */
export type Event = {
  /** Start time of the event. */
  timestamp: Time;

  /** Duration of the event. Omit or set to zero for an instant (point) event. */
  duration?: Duration;

  /** Event type definition for this event. Provides category name, display color, and optional platform ID for reconciliation. */
  event_type?: EventType;

  /** Typed property values matching the platform's structured properties model. */
  event_properties?: EventProperty[];

  /** Stable identity for deduplication during data platform ingestion. */
  id: string;

  /** Device ID this event is associated with. Use the platform device ID when known, or a local identifier (e.g. hostname, serial number). Required so consumers always know the source device. */
  device_id: string;
};
