// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { Color } from "./Color";
import { KeyValuePair } from "./KeyValuePair";
import { Time } from "./Time";

/** A discrete event that occurred at a specific time or over a time range */
export type Event = {
  /** Event start time */
  start_time: Time;

  /** Event end time. Omit for point events. */
  end_time?: Time;

  /** Display name for the event */
  label: string;

  /** Color used to visualize the event */
  color?: Color;

  /** Additional key-value metadata. Keys must be unique. */
  metadata?: KeyValuePair[];
};
