// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { EventPropertyType } from "./EventPropertyType";

/** A typed property value on an event, matching the platform's structured properties model */
export type EventProperty = {
  /** Property name */
  key: string;

  /** Value type */
  type: EventPropertyType;

  /** String-encoded value. Interpretation depends on type. */
  value: string;
};
