// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

/** Event type definition providing category name, display color, and optional platform ID for reconciliation during ingestion */
export type EventType = {
  /** Human-readable event type name (e.g. "Traffic event", "FAULT"). Used for filtering, grouping, and display. */
  name: string;

  /** Hex color string (e.g. "#FF5733"). Used by the player to color timeline markers. If absent, player assigns default. */
  color?: string;

  /** Platform event type UUID for reconciliation during ingestion. If present, platform matches by ID; if absent, falls back to name. */
  id?: string;
};
