// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { Quaternion } from "./Quaternion";
import { Time } from "./Time";
import { Vector3 } from "./Vector3";

/** A transform between two reference frames in 3D space. The transform describes the position and orientation of the child frame relative to the parent frame. */
export type FrameTransform = {
  /** Timestamp of transform */
  timestamp: Time;

  /** Name of the parent frame */
  parent_frame_id: string;

  /** Name of the child frame */
  child_frame_id: string;

  /**
   * Translation component of the transform: the position of the child frame's origin within the parent frame.
   * 
   * For example, a FrameTransform with a translation of (1, 0, 0) and an identity rotation means that a point at (0, 0, 0) in the child frame is at (1, 0, 0) in the parent frame.
   */
  translation: Vector3;

  /** Rotation component of the transform: the orientation of the child frame's axes relative to the parent frame */
  rotation: Quaternion;
};
