// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import type { FrameTransform } from "./FrameTransform.ts";

/** An array of FrameTransform messages */
export type FrameTransforms = {
  /** Array of transforms */
  transforms: FrameTransform[];
};
