// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { Quaternion } from "./Quaternion";
import { Time } from "./Time";
import { Vector3 } from "./Vector3";

/** A transform between two reference frames in 3D space. This transform can be used to convert the coordinates of a point from the child frame to the parent frame. */
export type FrameTransform = {
  /** Timestamp of transform */
  timestamp: Time;

  /** Name of the parent frame */
  parent_frame_id: string;

  /** Name of the child frame */
  child_frame_id: string;

  /**
   * Translation component of the transform: the position of the child frame's origin expressed in the parent frame.
   * 
   * To convert a point P from the child frame to the parent frame, first apply the rotation and then add the translation: P_parent = rotation * P_child + translation.
   * 
   * Example 1: With translation (1, 0, 0) and identity rotation, a point at (0, 0, 0) in the child frame maps to (1, 0, 0) in the parent frame.
   * 
   * Example 2: With translation (1, 2, 0) and a 90-degree rotation around the z-axis (quaternion x=0, y=0, z=0.707, w=0.707), a point at (1, 0, 0) in the child frame maps to (1, 3, 0) in the parent frame.
   */
  translation: Vector3;

  /** Rotation component of the transform: the rotation to apply to convert a point from the child frame to the parent frame */
  rotation: Quaternion;
};
