// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { Quaternion } from "./Quaternion";
import { Time } from "./Time";
import { Vector3 } from "./Vector3";

/** A transform between two reference frames in 3D space. This transform can be used to convert the coordinates of a point from the child frame to the parent frame. Foxglove applies the translation first and then the rotation: P_parent = rotation * (P_child + translation). */
export type FrameTransform = {
  /** Timestamp of transform */
  timestamp: Time;

  /** Name of the parent frame */
  parent_frame_id: string;

  /** Name of the child frame */
  child_frame_id: string;

  /**
   * Translation component of the transform, representing the position of the child frame's origin in the parent frame.
   * 
   * Examples:
   * 
   * 1. With translation (x=1, y=0, z=0) and identity rotation (x=0, y=0, z=0, w=1), a point at (x=0, y=0, z=0) in the child frame maps to (x=1, y=0, z=0) in the parent frame.
   * 
   * 2. With translation (x=1, y=2, z=0) and a 90-degree rotation around the z-axis (x=0, y=0, z=0.707, w=0.707), a point at (x=1, y=0, z=0) in the child frame maps to (x=-1, y=3, z=0) in the parent frame.
   */
  translation: Vector3;

  /** Rotation component of the transform, representing the orientation of the child frame in the parent frame */
  rotation: Quaternion;
};
