// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { LineageInfo } from "./LineageInfo";

/** GeoJSON data for annotating maps */
export type GeoJSON = {
  /** GeoJSON data encoded as a UTF-8 string */
  geojson: string;

  /** Unique identifier for this message (e.g., UUID7, ULID, or custom format) */
  message_id?: string;

  /** Lineage information for tracking data provenance */
  lineage?: LineageInfo;
};
