// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import type { CircleAnnotation } from "./CircleAnnotation.ts";
import type { PointsAnnotation } from "./PointsAnnotation.ts";
import type { TextAnnotation } from "./TextAnnotation.ts";

/** Array of annotations for a 2D image */
export type ImageAnnotations = {
  /** Circle annotations */
  circles: CircleAnnotation[];

  /** Points annotations */
  points: PointsAnnotation[];

  /** Text annotations */
  texts: TextAnnotation[];
};
