// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { CircleAnnotation } from "./CircleAnnotation";
import { LineageInfo } from "./LineageInfo";
import { PointsAnnotation } from "./PointsAnnotation";
import { TextAnnotation } from "./TextAnnotation";

/** Array of annotations for a 2D image */
export type ImageAnnotations = {
  /** Circle annotations */
  circles: CircleAnnotation[];

  /** Points annotations */
  points: PointsAnnotation[];

  /** Text annotations */
  texts: TextAnnotation[];

  /** Unique identifier for this message (e.g., UUID7, ULID, or custom format) */
  message_id?: string;

  /** Lineage information for tracking data provenance */
  lineage?: LineageInfo;
};
