// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

/** Reference to an input message used in lineage tracking */
export type InputReference = {
  /** Topic name of the input message */
  topic: string;

  /** Unique identifier of the input message (e.g., UUID7, ULID, or custom format) */
  message_id: string;
};
