// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { JointState } from "./JointState";
import { Time } from "./Time";

/** The state of a set of joints at a given time. All joint states in one message are recorded at the same time. */
export type JointStates = {
  /** Timestamp of the joint states */
  timestamp: Time;

  /** Joint states */
  joints: JointState[];
};
