// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { Time } from "./Time";

/**
  * The state of a set of joints. The state of each joint (revolute or prismatic) is defined by its position, velocity, and effort (force or torque). Each joint is uniquely identified by its name.
  * 
  * This message consists of multiple arrays, one for each part of the joint state. Each array can be left empty if that data is not available. All non-empty arrays must have the same length.
 */
export type JointState = {
  /** Timestamp at which the joint states were recorded. All joint states in one message must be recorded at the same time. */
  timestamp: Time;

  /** Joint names. If non-empty, must have the same length as all other non-empty arrays. The name is used to uniquely associate each joint with its corresponding position, velocity, and effort values. */
  name: string[];

  /** Joint positions. Radians for revolute joints, meters for prismatic joints. Can be empty if position data is not available. */
  position: number[];

  /** Joint velocities. Rad/s for revolute joints, m/s for prismatic joints. Can be empty if velocity data is not available. */
  velocity: number[];

  /** Joint efforts (force or torque). Nm for revolute joints, N for prismatic joints. Can be empty if effort data is not available. */
  effort: number[];
};
