// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { InputReference } from "./InputReference";
import { StateReference } from "./StateReference";

/** Lineage information for tracking data provenance through a processing pipeline */
export type LineageInfo = {
  /** References to input messages that contributed to this message */
  inputs: InputReference[];

  /** Name of the processing node that produced this message */
  processing_node: string;

  /** Optional reference to the state of the processing node */
  state?: StateReference;
};
