// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import type { LocationFix } from "./LocationFix.ts";

/** A group of LocationFix messages */
export type LocationFixes = {
  /** An array of location fixes */
  fixes: LocationFix[];
};
