// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { Color } from "./Color";
import { LocationFix } from "./LocationFix";

/** A group of LocationFix messages */
export type LocationFixes = {
  /** One or more location fixes */
  fixes: LocationFix[];

  /** Color used to visualize this series, if not set on the individual fixes */
  color: Color;
};
