// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { LocationFix } from "./LocationFix";

/** A group of LocationFix messages */
export type LocationFixes = {
  /** One or more location fixes */
  fixes: LocationFix[];
};
