// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { Color } from "./Color";
import { KeyValuePair } from "./KeyValuePair";
import { PositionCovarianceType } from "./PositionCovarianceType";
import { Time } from "./Time";

/** A navigation satellite fix for any Global Navigation Satellite System */
export type LocationFix = {
  /** Timestamp of the message */
  timestamp: Time;

  /** Frame for the sensor. Latitude and longitude readings are at the origin of the frame. */
  frame_id: string;

  /** Latitude in degrees */
  latitude: number;

  /** Longitude in degrees */
  longitude: number;

  /** Altitude in meters */
  altitude: number;

  /** Position covariance (m^2) defined relative to a tangential plane through the reported position. The components are East, North, and Up (ENU), in row-major order. */
  position_covariance: [number, number, number, number, number, number, number, number, number];

  /** If `position_covariance` is available, `position_covariance_type` must be set to indicate the type of covariance. */
  position_covariance_type: PositionCovarianceType;

  /** Compass heading in radians, measured clockwise from true north */
  heading?: number;

  /** Heading variance in rad^2 */
  heading_variance?: number;

  /** Velocity in the east direction (longitude axis) in m/s, positive east. */
  velocity_x?: number;

  /** Velocity in the north direction (latitude axis) in m/s, positive north. */
  velocity_y?: number;

  /** Velocity in the vertical (altitude) direction in m/s, positive up. */
  velocity_z?: number;

  /** Color used to visualize the location */
  color?: Color;

  /** Additional user-provided metadata associated with the location fix. Keys must be unique. */
  metadata?: KeyValuePair[];
};
