// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { LogLevel } from "./LogLevel";
import { Timestamp } from "./Timestamp";

/** A log message */
export type Log = {
  /** Timestamp of log message */
  timestamp: Timestamp;

  /** Log level */
  level: LogLevel;

  /** Log message */
  message: string;

  /** Process or node name */
  name: string;

  /** Filename */
  file: string;

  /** Line number in the file */
  line: number;
};
