// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import type { LogLevel } from "./LogLevel";
import type { Time } from "./Time";

/** A log message */
export type Log = {
  /** Timestamp of log message */
  timestamp: Time;

  /** Log level */
  level: LogLevel;

  /** Log message */
  message: string;

  /** Process or node name */
  name: string;

  /** Filename */
  file: string;

  /** Line number in the file */
  line: number;
};
