// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

/** Shape of the marker used for map visualization */
export enum MarkerShape {
  /** Diamond-shaped marker */
  DIAMOND = 0,

  /** Square marker */
  SQUARE = 1,

  /** Cross-shaped marker */
  CROSS = 2,

  /** X-shaped marker */
  X = 3,

  /** Dot marker */
  DOT = 4,

  /** Pin marker */
  PIN = 5,
}
