// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

/** Style of point used for map visualization */
export enum PointStyle {
  /** Dot marker */
  DOT = 0,

  /** Diamond-shaped marker */
  DIAMOND = 1,

  /** Square marker */
  SQUARE = 2,

  /** Plus-shaped marker (+) */
  PLUS = 3,

  /** Cross-shaped marker (x) */
  CROSS = 4,

  /** Pin marker */
  PIN = 5,
}
