// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { Point2 } from "./Point2";
import { Time } from "./Time";

/** A timestamped point for a position in 2D space */
export type Point2InFrame = {
  /** Timestamp of point */
  timestamp: Time;

  /** Frame of reference for point position */
  frame_id: string;

  /** Point in 2D space */
  point: Point2;
};
