// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import type { Point3 } from "./Point3.ts";
import type { Time } from "./Time.ts";

/** A timestamped point for a position in 3D space */
export type Point3InFrame = {
  /** Timestamp of point */
  timestamp: Time;

  /** Frame of reference for point position */
  frame_id: string;

  /** Point in 3D space */
  point: Point3;
};
