// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import type { Color } from "./Color.ts";
import type { Point2 } from "./Point2.ts";
import type { PointsAnnotationType } from "./PointsAnnotationType.ts";
import type { Time } from "./Time.ts";

/** An array of points on a 2D image */
export type PointsAnnotation = {
  /** Timestamp of annotation */
  timestamp: Time;

  /** Type of points annotation to draw */
  type: PointsAnnotationType;

  /**
   * Points in 2D image coordinates (pixels).
   * These coordinates use the top-left corner of the top-left pixel of the image as the origin.
   */
  points: Point2[];

  /** Outline color */
  outline_color: Color;

  /** Per-point colors, if `type` is `POINTS`, or per-segment stroke colors, if `type` is `LINE_LIST`, `LINE_STRIP` or `LINE_LOOP`. */
  outline_colors: Color[];

  /** Fill color */
  fill_color: Color;

  /** Stroke thickness in pixels */
  thickness: number;
};
