// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { LineageInfo } from "./LineageInfo";
import { Pose } from "./Pose";
import { Time } from "./Time";

/** A timestamped pose for an object or reference frame in 3D space */
export type PoseInFrame = {
  /** Timestamp of pose */
  timestamp: Time;

  /** Frame of reference for pose position and orientation */
  frame_id: string;

  /** Pose in 3D space */
  pose: Pose;

  /** Unique identifier for this message (e.g., UUID7, ULID, or custom format) */
  message_id?: string;

  /** Lineage information for tracking data provenance */
  lineage?: LineageInfo;
};
