// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import type { Pose } from "./Pose.ts";
import type { Time } from "./Time.ts";

/** A timestamped pose for an object or reference frame in 3D space */
export type PoseInFrame = {
  /** Timestamp of pose */
  timestamp: Time;

  /** Frame of reference for pose position and orientation */
  frame_id: string;

  /** Pose in 3D space */
  pose: Pose;
};
