// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import type { Quaternion } from "./Quaternion.ts";
import type { Vector3 } from "./Vector3.ts";

/** A position and orientation for an object or reference frame in 3D space */
export type Pose = {
  /** Point denoting position in 3D space */
  position: Vector3;

  /** Quaternion denoting orientation in 3D space */
  orientation: Quaternion;
};
