// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

/** Type of position covariance */
export enum PositionCovarianceType {
  /** Unknown position covariance type */
  UNKNOWN = 0,

  /** Position covariance is approximated */
  APPROXIMATED = 1,

  /** Position covariance is diagonal */
  DIAGONAL_KNOWN = 2,

  /** Position covariance is known */
  KNOWN = 3,
}
