// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { Time } from "./Time";

/** A single block of an audio bitstream */
export type RawAudio = {
  /** Timestamp of the start of the audio block */
  timestamp: Time;

  /**
   * Audio data. Samples must be interleaved. Multibyte samples must be little-endian.
   * - `pcm-s16`
   *   - Each sample is a signed 16-bit PCM value.
   * - `g711-alaw`
   *   - Each byte is one G.711 A-law encoded sample. Data contains raw samples without WAV, container, or RTP headers. The byte length must be divisible by `number_of_channels` so the block contains complete sample frames.
   * - `g711-ulaw`
   *   - Each byte is one G.711 mu-law encoded sample. Data contains raw samples without WAV, container, or RTP headers. The byte length must be divisible by `number_of_channels` so the block contains complete sample frames.
   */
  data: Uint8Array;

  /** Audio format. Values defined by this schema are `pcm-s16`, `g711-alaw`, and `g711-ulaw`. Consumers may support a subset of these formats. */
  format: string;

  /** Sample rate in Hz. For G.711 formats, this must be greater than zero. */
  sample_rate: number;

  /** Number of channels in the audio block. For G.711 formats, this must be greater than zero. */
  number_of_channels: number;
};
