// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { Time } from "./Time";

/** A single frame of an audio bit stream */
export type RawAudio = {
  /** Timestamp of the audio frame */
  timestamp: Time;

  /** Audio frame data. The samples in the data must be interleaved and little-endian */
  data: Uint8Array;

  /** Audio format. Only 'pcm-s16' is currently supported */
  format: string;

  /** Sample rate in Hz */
  sample_rate: number;

  /** Number of channels in the audio frame */
  number_of_channels: number;
};
