// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { SceneEntityDeletionType } from "./SceneEntityDeletionType";
import { Timestamp } from "./Timestamp";

/** Command to remove previously published entities */
export type SceneEntityDeletion = {
  /** Timestamp of the deletion. Only matching entities earlier than this timestamp will be deleted. */
  timestamp: Timestamp;

  /** Type of deletion action to perform */
  type: SceneEntityDeletionType;

  /** Identifier which must match if `type` is `MATCHING_ID`. */
  id: string;
};
