// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import type { SceneEntityDeletionType } from "./SceneEntityDeletionType.ts";
import type { Time } from "./Time.ts";

/** Command to remove previously published entities */
export type SceneEntityDeletion = {
  /** Timestamp of the deletion. Only matching entities earlier than this timestamp will be deleted. */
  timestamp: Time;

  /** Type of deletion action to perform */
  type: SceneEntityDeletionType;

  /** Identifier which must match if `type` is `MATCHING_ID`. */
  id: string;
};
