// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import type { SceneEntity } from "./SceneEntity.ts";
import type { SceneEntityDeletion } from "./SceneEntityDeletion.ts";

/** An update to the entities displayed in a 3D scene */
export type SceneUpdate = {
  /** Scene entities to delete */
  deletions: SceneEntityDeletion[];

  /** Scene entities to add or replace */
  entities: SceneEntity[];
};
