// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import type { ArrowPrimitive } from "./ArrowPrimitive.ts";
import type { CubePrimitive } from "./CubePrimitive.ts";
import type { CylinderPrimitive } from "./CylinderPrimitive.ts";
import type { Duration } from "./Duration.ts";
import type { KeyValuePair } from "./KeyValuePair.ts";
import type { LinePrimitive } from "./LinePrimitive.ts";
import type { ModelPrimitive } from "./ModelPrimitive.ts";
import type { SpherePrimitive } from "./SpherePrimitive.ts";
import type { TextPrimitive } from "./TextPrimitive.ts";
import type { Time } from "./Time.ts";
import type { TriangleListPrimitive } from "./TriangleListPrimitive.ts";

/** A visual element in a 3D scene. An entity may be composed of multiple primitives which all share the same frame of reference. */
export type SceneEntity = {
  /** Timestamp of the entity */
  timestamp: Time;

  /** Frame of reference */
  frame_id: string;

  /** Identifier for the entity. A entity will replace any prior entity on the same topic with the same `id`. */
  id: string;

  /** Length of time (relative to `timestamp`) after which the entity should be automatically removed. Zero value indicates the entity should remain visible until it is replaced or deleted. */
  lifetime: Duration;

  /** Whether the entity should keep its location in the fixed frame (false) or follow the frame specified in `frame_id` as it moves relative to the fixed frame (true) */
  frame_locked: boolean;

  /** Additional user-provided metadata associated with the entity. Keys must be unique. */
  metadata: KeyValuePair[];

  /** Arrow primitives */
  arrows: ArrowPrimitive[];

  /** Cube primitives */
  cubes: CubePrimitive[];

  /** Sphere primitives */
  spheres: SpherePrimitive[];

  /** Cylinder primitives */
  cylinders: CylinderPrimitive[];

  /** Line primitives */
  lines: LinePrimitive[];

  /** Triangle list primitives */
  triangles: TriangleListPrimitive[];

  /** Text primitives */
  texts: TextPrimitive[];

  /** Model primitives */
  models: ModelPrimitive[];
};
