// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { LineageInfo } from "./LineageInfo";
import { SceneEntityDeletionType } from "./SceneEntityDeletionType";
import { Time } from "./Time";

/** Command to remove previously published entities */
export type SceneEntityDeletion = {
  /** Timestamp of the deletion. Only matching entities earlier than this timestamp will be deleted. */
  timestamp: Time;

  /** Type of deletion action to perform */
  type: SceneEntityDeletionType;

  /** Identifier which must match if `type` is `MATCHING_ID`. */
  id: string;

  /** Unique identifier for this message (e.g., UUID7, ULID, or custom format) */
  message_id?: string;

  /** Lineage information for tracking data provenance */
  lineage?: LineageInfo;
};
