// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { LineageInfo } from "./LineageInfo";
import { SceneEntity } from "./SceneEntity";
import { SceneEntityDeletion } from "./SceneEntityDeletion";

/** An update to the entities displayed in a 3D scene */
export type SceneUpdate = {
  /** Scene entities to delete */
  deletions: SceneEntityDeletion[];

  /** Scene entities to add or replace */
  entities: SceneEntity[];

  /** Unique identifier for this message (e.g., UUID7, ULID, or custom format) */
  message_id?: string;

  /** Lineage information for tracking data provenance */
  lineage?: LineageInfo;
};
