// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { CameraCalibration } from "./CameraCalibration";
import { Grid } from "./Grid";
import { LaserScan } from "./LaserScan";
import { PointCloud } from "./PointCloud";
import { PoseInFrame } from "./PoseInFrame";
import { PosesInFrame } from "./PosesInFrame";
import { SceneEntity } from "./SceneEntity";
import { Time } from "./Time";
import { VoxelGrid } from "./VoxelGrid";

/** Information about a selected entity in a visualization panel */
export type SelectedEntity = {
  /** Timestamp of the selection */
  timestamp: Time;

  /** Frame of reference for the selected entity */
  frame_id: string;

  /** Topic from which the entity originated */
  source_topic: string;

  /** Schema name of the source message */
  source_schema_name: string;

  /** Identifier of the selected entity */
  entity_id: string;

  /** Selected scene entity */
  scene_entity?: SceneEntity;

  /** Selected point cloud */
  point_cloud?: PointCloud;

  /** Selected laser scan */
  laser_scan?: LaserScan;

  /** Selected grid */
  grid?: Grid;

  /** Selected voxel grid */
  voxel_grid?: VoxelGrid;

  /** Selected camera calibration */
  camera_calibration?: CameraCalibration;

  /** Selected pose in frame */
  pose_in_frame?: PoseInFrame;

  /** Selected poses in frame */
  poses_in_frame?: PosesInFrame;
};
