// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { CameraCalibration } from "./CameraCalibration";
import { Grid } from "./Grid";
import { KeyValuePair } from "./KeyValuePair";
import { LaserScan } from "./LaserScan";
import { PointCloud } from "./PointCloud";
import { PoseInFrame } from "./PoseInFrame";
import { PosesInFrame } from "./PosesInFrame";
import { SceneEntity } from "./SceneEntity";
import { VoxelGrid } from "./VoxelGrid";

/** Information about a selected entity in a visualization panel */
export type SelectedEntity = {
  /** Topic from which the entity originated */
  source_topic: string;

  /** Schema name of the source message */
  source_schema_name: string;

  /** Selected scene entity */
  scene_entity?: SceneEntity;

  /** Selected point cloud */
  point_cloud?: PointCloud;

  /** Selected laser scan */
  laser_scan?: LaserScan;

  /** Selected grid */
  grid?: Grid;

  /** Selected voxel grid */
  voxel_grid?: VoxelGrid;

  /** Selected camera calibration */
  camera_calibration?: CameraCalibration;

  /** Selected pose in frame */
  pose_in_frame?: PoseInFrame;

  /** Selected poses in frame */
  poses_in_frame?: PosesInFrame;

  /** Additional user-provided metadata associated with the selected entity. */
  metadata?: KeyValuePair[];
};
