// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import type { Color } from "./Color.ts";
import type { Pose } from "./Pose.ts";
import type { Vector3 } from "./Vector3.ts";

/** A primitive representing a sphere or ellipsoid */
export type SpherePrimitive = {
  /** Position of the center of the sphere and orientation of the sphere */
  pose: Pose;

  /** Size (diameter) of the sphere along each axis */
  size: Vector3;

  /** Color of the sphere */
  color: Color;
};
