// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

/** Reference to a state message used in lineage tracking */
export type StateReference = {
  /** Topic name of the state message */
  topic: string;

  /** Unique identifier of the state message (e.g., UUID7, ULID, or custom format) */
  message_id: string;
};
