// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

/** A timestamp composed of seconds and nanoseconds */
export type Timestamp = {
  /** The number of seconds since a user-defined epoch */
  sec: number;

  /** The number of nanoseconds since the sec value */
  nsec: number;
};
