// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

/** A velocity vector in 3D space. Deprecated: use Vector3. */
export type Velocity3 = {
  /** x component */
  x: number;

  /** y component */
  y: number;

  /** z component */
  z: number;
};
