// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

/** A velocity vector in 3D space */
export type Velocity3 = {
  /** x velocity in m/s */
  x: number;

  /** y velocity in m/s */
  y: number;

  /** z velocity in m/s */
  z: number;
};
