// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

/** A velocity vector in 3D space */
export type Velocity3 = {
  /** Velocity east (longitude axis) in m/s. */
  x: number;

  /** Velocity north (latitude axis) in m/s. */
  y: number;

  /** Velocity up (altitude axis) in m/s. */
  z: number;
};
