# generated by datamodel-codegen:
#   filename:  base_panel.json
#   timestamp: 2025-11-11T17:09:34+00:00

from __future__ import annotations

from dataclasses import dataclass

from ..dataclass_model import DataclassModel


@dataclass(kw_only=True)
class BasePanel(DataclassModel):
    """
    A base panel in Foxglove
    """

    type: str
    """
    The type of the panel
    """
