# generated by datamodel-codegen:
#   filename:  base_panel.json

from __future__ import annotations

from dataclasses import dataclass

from ..dataclass_model import DataclassModel


@dataclass(kw_only=True)
class BasePanel(DataclassModel):
    """
    Base panel for all panels in a Foxglove layout. All panels must inherit from this base panel.
    """

    type: str
    """
    The type of the panel
    """
