# generated by datamodel-codegen:
#   filename:  layout.json
#   timestamp: 2025-11-13T18:12:40+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Literal

from ..dataclass_model import DataclassModel
from . import base_panel


@dataclass(kw_only=True)
class Variables(DataclassModel):
    pass


@dataclass(kw_only=True)
class Layout(DataclassModel):
    """
    A layout in Foxglove
    """

    version: Literal["0.0.1"]
    """
    The version of the layout format
    """
    variables: Variables
    items: ItemList


@dataclass(kw_only=True)
class Tab(DataclassModel):
    id: str
    """
    The unique identifier for the tab
    """
    name: str
    """
    The name of the tab
    """
    items: ItemList


@dataclass(kw_only=True)
class Tabs(DataclassModel):
    tabs: List[Tab]
    selected_tab_id: str | None = None
    """
    The unique identifier for the selected tab
    """


@dataclass(kw_only=True)
class Item(DataclassModel):
    """
    An item in a layout with a ratio for space allocation.

    The ratio determines the proportion of space this item takes up, similar to CSS flex ratio.
    For example, if a list has 3 items with ratios 1, 2, and 3, the first item takes 1/6 of the
    space, the second item takes 2/6, and the third item takes 3/6.
    """

    ratio: float
    """
    Proportion of space this item occupies
    """
    content: base_panel.BasePanel | Tabs | ItemList
    """
    Content of the item (panel, tabs, or item list)
    """


@dataclass(kw_only=True)
class ItemList(DataclassModel):
    direction: Literal["vertical", "horizontal"]
    items: List[Item]
