# generated by datamodel-codegen:
#   filename:  layouts.json
#   timestamp: 2025-11-11T17:09:34+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Literal

from ..dataclass_model import DataclassModel
from . import base_panel


@dataclass(kw_only=True)
class Variables(DataclassModel):
    pass


@dataclass(kw_only=True)
class UserScript(DataclassModel):
    name: str
    """
    The name of the user script
    """
    source_code: str
    """
    The source code of the user script
    """


@dataclass(kw_only=True)
class Layout(DataclassModel):
    """
    A layout in Foxglove
    """

    version: str
    """
    The version of the layout format
    """
    variables: Variables
    items: ItemList
    user_nodes: Dict[str, UserScript]


@dataclass(kw_only=True)
class Tab(DataclassModel):
    id: str
    """
    The unique identifier for the tab
    """
    name: str
    """
    The name of the tab
    """
    items: ItemList


@dataclass(kw_only=True)
class Tabs(DataclassModel):
    tabs: List[Tab]
    selected_tab_id: str | None = None
    """
    The unique identifier for the selected tab
    """


@dataclass(kw_only=True)
class Item(DataclassModel):
    ratio: float
    """
    The ratio of the item
    """
    content: base_panel.BasePanel | Tabs | ItemList


@dataclass(kw_only=True)
class ItemList(DataclassModel):
    direction: Literal["vertical", "horizontal"]
    items: List[Item]
