# generated by datamodel-codegen:
#   filename:  markdown_panel.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from ..dataclass_model import DataclassModel
from .base_panel import BasePanel


@dataclass(kw_only=True)
class MarkdownConfig(DataclassModel):
    markdown: str | None = None
    """
    The Markdown content to display
    """
    font_size: Literal[8, 9, 10, 11, 12, 14, 16, 18, 24, 30, 36, 48, 60, 72] | None = 12
    """
    The font size to use for the Markdown content
    """
    foxglove_panel_title: str | None = None
    """
    The title of the panel in Foxglove
    """


@dataclass(kw_only=True)
class MarkdownPanel(BasePanel):
    """
    Displays Github flavored Markdown within a layout. Check out [the documentation](https://docs.foxglove.dev/docs/visualization/panels/markdown) for more information.
    """

    config: MarkdownConfig
    type: Literal["Markdown"] = "Markdown"
