# generated by datamodel-codegen:
#   filename:  markdown_panel.json
#   timestamp: 2025-11-11T17:09:34+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from ..dataclass_model import DataclassModel
from .base_panel import BasePanel


@dataclass(kw_only=True)
class MarkdownConfig(DataclassModel):
    markdown: str | None = None
    """
    The Markdown content to display
    """
    font_size: Literal[8, 9, 10, 11, 12, 14, 16, 18, 24, 30, 36, 48, 60, 72] | None = 12
    """
    The font size to use for the Markdown content
    """
    foxglove_panel_title: str | None = None
    """
    The title of the panel in Foxglove
    """


@dataclass(kw_only=True)
class MarkdownPanel(BasePanel):
    """
    A Markdown panel in Foxglove
    """

    config: MarkdownConfig
    type: Literal["Markdown"] = "Markdown"
