# generated by datamodel-codegen:
#   filename:  panel.json
#   timestamp: 2025-11-11T17:09:34+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict

from .base_panel import BasePanel


@dataclass(kw_only=True)
class Panel(BasePanel):
    """
    A generic panel in Foxglove
    """

    config: Dict[str, Any]
    """
    The config of the panel. This can be an arbitrary JSON serializable object.
    """
