# generated by datamodel-codegen:
#   filename:  state_transitions_panel.json
#   timestamp: 2025-11-13T18:12:40+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Literal

from ..dataclass_model import DataclassModel
from .base_panel import BasePanel


@dataclass(kw_only=True)
class BaseCustomState(DataclassModel):
    label: str | None = None
    """
    The label of the custom state
    """
    color: str | None = None
    """
    The color of the custom state
    """


@dataclass(kw_only=True)
class StateTransitionsDiscreteCustomState(BaseCustomState):
    value: str | None = ""
    """
    The value of the custom state
    """


@dataclass(kw_only=True)
class StateTransitionsRangeCustomState(BaseCustomState):
    value: float | None = None
    """
    The value of the custom state
    """
    operator: Literal["=", "<", "<=", ">", ">="] | None = "<"


@dataclass(kw_only=True)
class StateTransitionsRangeCustomStates(DataclassModel):
    type: Literal["range"] = "range"
    states: List[StateTransitionsRangeCustomState] | None = None
    otherwise: BaseCustomState | None = None


@dataclass(kw_only=True)
class StateTransitionsDiscreteCustomStates(DataclassModel):
    type: Literal["discrete"] = "discrete"
    states: List[StateTransitionsDiscreteCustomState] | None = None


@dataclass(kw_only=True)
class StateTransitionsPath(DataclassModel):
    value: str
    """
    The value of the path
    """
    enabled: bool
    label: str | None = None
    """
    The label of the path
    """
    timestamp_method: (
        Literal["receiveTime", "publishTime", "headerStamp", "customField"] | None
    ) = "receiveTime"
    timestamp_path: str | None = None
    """
    The path of the timestamp
    """
    custom_states: (
        StateTransitionsRangeCustomStates | StateTransitionsDiscreteCustomStates | None
    ) = None


@dataclass(kw_only=True)
class StateTransitionsConfig(DataclassModel):
    paths: List[StateTransitionsPath] | None = None
    is_synced: bool | None = True
    x_axis_max_value: float | None = None
    """
    The maximum value of the x-axis
    """
    x_axis_min_value: float | None = None
    """
    The minimum value of the x-axis
    """
    x_axis_range: float | None = None
    """
    The range of the x-axis
    """
    x_axis_label: str | None = None
    """
    The label of the x-axis
    """
    time_window_mode: Literal["automatic", "sliding", "fixed"] | None = "automatic"
    """
    The mode of the time window
    """
    playback_bar_position: Literal["center", "right"] | None = "center"
    """
    The position of the playback bar
    """
    show_points: bool | None = False
    foxglove_panel_title: str | None = None
    """
    The title of the panel in Foxglove
    """


@dataclass(kw_only=True)
class StateTransitionsPanel(BasePanel):
    """
    The State Transitions panel visualizes changes in discrete values from your topic message paths. Check out [the documentation](https://docs.foxglove.dev/docs/visualization/panels/state-transitions) for more information.
    """

    config: StateTransitionsConfig
    type: Literal["StateTransitions"] = "StateTransitions"
