// Backward compatibility - implementations are now in messages.cpp.
// This file is kept for build systems that may reference it.
// Generated by https://github.com/foxglove/foxglove-sdk

#include "messages.cpp"
