// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { CircleAnnotation } from "./CircleAnnotation";
import { KeyValuePair } from "./KeyValuePair";
import { PointsAnnotation } from "./PointsAnnotation";
import { TextAnnotation } from "./TextAnnotation";

/** Array of annotations for a 2D image */
export type ImageAnnotations = {
  /** Circle annotations */
  circles: CircleAnnotation[];

  /** Points annotations */
  points: PointsAnnotation[];

  /** Text annotations */
  texts: TextAnnotation[];

  /** Additional user-provided metadata associated with the image annotations. Keys must be unique. */
  metadata?: KeyValuePair[];
};
