// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

/** The state of a single joint (revolute or prismatic). */
export type JointState = {
  /** Joint name */
  name: string;

  /** Joint position. Radians for revolute joints, meters for prismatic joints. Use NaN to indicate that the value is not present if the message definition does not support optional fields. */
  position?: number;

  /** Joint velocity. Rad/s for revolute joints, m/s for prismatic joints. Use NaN to indicate that the value is not present if the message definition does not support optional fields. */
  velocity?: number;

  /** Joint acceleration. Rad/s² for revolute joints, m/s² for prismatic joints. Use NaN to indicate that the value is not present if the message definition does not support optional fields. */
  acceleration?: number;

  /** Joint effort (force or torque). Nm for revolute joints, N for prismatic joints. Use NaN to indicate that the value is not present if the message definition does not support optional fields. */
  effort?: number;
};
