[package]
name = "example-channelless"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
foxglove = { path = "../../foxglove" }
env_logger = "0.11.5"
mcap.workspace = true
schemars = "0.8.21"
serde = { version = "1.0", features = ["derive"] }
