# https://github.com/mozilla/cbindgen/blob/master/docs.md#cbindgentoml

language = "C"
cpp_compat = true
include_guard = "FOXGLOVE_C_H"
header = """
/*
 * Foxglove SDK
 * https://github.com/foxglove/foxglove-sdk
 */
"""

[export.rename]
"FoxgloveWebSocketServer" = "foxglove_websocket_server"
