/*
 * NOTE: This file is autogenerated by cbindgen.
 *
 * Foxglove Agent SDK
 */


#ifndef AGENT_SDK_H
#define AGENT_SDK_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#ifndef FOXGLOVE_NONNULL
#define FOXGLOVE_NONNULL
#endif


#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

int32_t foxglove_add(int32_t x, int32_t y);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* AGENT_SDK_H */
