// Pure helpers for the netem viewer relay (`yarn netem-relay`): WireGuard
// config templating and tunnel-subnet derivation. Kept free of process/fs/
// docker access so the templating and the AllowedIPs scoping invariant are
// unit-testable. The CLI side lives in scripts/netemRelay.ts; the container
// side is docker-compose.netem-relay.yml.

/** The perlink network subnet (docker-compose.netem-livekit.yml). */
export const PERLINK_SUBNET = "10.99.0.0/24";

/** The netem-targets network subnet (docker-compose.netem-perlink.yml). */
const NETEM_TARGETS_SUBNET = "10.98.0.0/24";

/** The relay's static IP on the perlink network (docker-compose.netem-relay.yml). */
export const RELAY_PERLINK_IP = "10.99.0.60";

/** LiveKit's static IP on the perlink network (docker-compose.netem-livekit.yml). */
export const LIVEKIT_PERLINK_IP = "10.99.0.2";

/** The WireGuard listen port, published 1:1 to the host by the relay overlay. */
export const WG_LISTEN_PORT = 51820;

/**
 * Default tunnel subnet. Chosen to avoid the stack's own subnets (10.98/24,
 * 10.99/24) and common LAN ranges; overridable via NETEM_RELAY_TUNNEL_SUBNET.
 */
export const DEFAULT_TUNNEL_SUBNET = "10.200.0.0/24";

/** Addresses derived from the tunnel subnet, shared by both tunnel endpoints. */
export interface TunnelAddressing {
  /** The tunnel subnet in CIDR form, e.g. "10.200.0.0/24". */
  subnet: string;
  /** Relay-side wg0 address with prefix, e.g. "10.200.0.1/24". */
  relayAddress: string;
  /** Host-side tunnel address with prefix, e.g. "10.200.0.2/24". */
  hostAddress: string;
  /** Host address as a /32, for the relay's peer AllowedIPs. */
  hostPeerAllowedIp: string;
}

/**
 * Derive the relay (.1) and host (.2) tunnel addresses from a /24 subnet.
 * Rejects malformed subnets and subnets that collide with the stack's own
 * networks (where routing through the tunnel would loop or shadow the stack).
 */
export function deriveTunnelAddressing(subnet: string): TunnelAddressing {
  const match = /^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.0\/24$/.exec(subnet);
  if (match == null) {
    throw new Error(
      `Invalid tunnel subnet '${subnet}': expected a /24 in dotted form ending in .0, e.g. ${DEFAULT_TUNNEL_SUBNET}`,
    );
  }
  const octets = match.slice(1, 4).map(Number);
  if (octets.some((o) => o > 255)) {
    throw new Error(`Invalid tunnel subnet '${subnet}': octet out of range`);
  }
  if (subnet === PERLINK_SUBNET || subnet === NETEM_TARGETS_SUBNET) {
    throw new Error(
      `Invalid tunnel subnet '${subnet}': collides with the netem stack's own networks (${NETEM_TARGETS_SUBNET}, ${PERLINK_SUBNET})`,
    );
  }
  const base = octets.join(".");
  return {
    subnet,
    relayAddress: `${base}.1/24`,
    hostAddress: `${base}.2/24`,
    hostPeerAllowedIp: `${base}.2/32`,
  };
}

/**
 * Validate that a value looks like a WireGuard key (32 bytes, base64). Guards
 * against accidentally templating a file path or empty string into a config.
 */
export function assertWgKey(value: string, what: string): void {
  if (!/^[A-Za-z0-9+/]{43}=$/.test(value)) {
    throw new Error(`${what} does not look like a WireGuard key`);
  }
}

/** Inputs for the relay-side (container) WireGuard config. */
export interface RelayConfigParams {
  relayPrivateKey: string;
  hostPublicKey: string;
  /** The host's tunnel address as a /32 (TunnelAddressing.hostPeerAllowedIp). */
  hostPeerAllowedIp: string;
}

/**
 * Build the relay-side config, applied inside the container via
 * `wg setconf` (so no Address/MTU keys — those are wg-quick extensions; the
 * compose overlay assigns the interface address itself).
 */
export function buildRelayConfig(params: RelayConfigParams): string {
  assertWgKey(params.relayPrivateKey, "relay private key");
  assertWgKey(params.hostPublicKey, "host public key");
  return [
    "# Generated by `yarn netem-relay` — do not edit.",
    "[Interface]",
    `ListenPort = ${WG_LISTEN_PORT}`,
    `PrivateKey = ${params.relayPrivateKey}`,
    "",
    "[Peer]",
    `PublicKey = ${params.hostPublicKey}`,
    `AllowedIPs = ${params.hostPeerAllowedIp}`,
    "",
  ].join("\n");
}

/** Inputs for the host-side (macOS) wg-quick config. */
export interface HostConfigParams {
  hostPrivateKey: string;
  relayPublicKey: string;
  /** The host's tunnel address with prefix (TunnelAddressing.hostAddress). */
  hostAddress: string;
}

/**
 * Build the host-side wg-quick config. AllowedIPs is fixed to the perlink
 * subnet by construction — it is deliberately not a parameter. Routing
 * anything broader through the tunnel lets ICE discover a candidate pair that
 * bypasses the impaired path (or hijacks unrelated host traffic).
 */
export function buildHostConfig(params: HostConfigParams): string {
  assertWgKey(params.hostPrivateKey, "host private key");
  assertWgKey(params.relayPublicKey, "relay public key");
  return [
    "# Generated by `yarn netem-relay` — do not edit.",
    "# Bring up/down with: sudo wg-quick up/down <absolute path to this file>",
    "[Interface]",
    `PrivateKey = ${params.hostPrivateKey}`,
    `Address = ${params.hostAddress}`,
    "",
    "[Peer]",
    `PublicKey = ${params.relayPublicKey}`,
    `Endpoint = 127.0.0.1:${WG_LISTEN_PORT}`,
    "# Route ONLY the perlink subnet through the tunnel. Widening this lets ICE",
    "# select an unimpaired path that silently bypasses netem.",
    `AllowedIPs = ${PERLINK_SUBNET}`,
    "# Keepalives hold the docker-proxy UDP mapping open across idle periods.",
    "PersistentKeepalive = 25",
    "",
  ].join("\n");
}
