name: Install common dependencies

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v6
      with:
        python-version: "3.10"

    - uses: astral-sh/setup-uv@v6

    # disable man-db to speed up apt install
    - shell: bash
      run: sudo rm -f /var/lib/man-db/auto-update

    - shell: bash
      run: sudo apt-get update

    - shell: bash
      run: |
        sudo apt-get install -y --no-install-recommends \
          libprotobuf-dev \
          protobuf-compiler \
          build-essential \
          pkg-config \
          cmake \
          libglib2.0-dev
