// Generated by https://github.com/foxglove/foxglove-sdk

#pragma once

// Include the new messages header.
#include <foxglove/messages.hpp>

// Provide backward-compatible namespace alias.
namespace foxglove {
namespace schemas = messages;
}  // namespace foxglove
