name: Rust Data Provider Example

on:
  workflow_call: {}

jobs:
  build:
    name: Build Rust Data Provider Example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          repository: foxglove/foxglove-sdk
          ref: ${{ github.workflow_sha }}

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build the example
        run: cargo build --release -p example_data_provider

      - name: Upload binary to artifacts
        uses: actions/upload-artifact@v6
        with:
          name: example_data_provider
          path: target/release/example_data_provider
          if-no-files-found: error
