[package]
name = "example_agent"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
foxglove = { path = "../../foxglove", features = ["schemars", "agent"] }
tokio = { version = "1.47", features = ["full"] }
clap = { version = "4.5", features = ["derive"] }
env_logger = "0.11.5"
serde_json = "1.0.142"
